services:
  db:
    image: postgres
    restart: always
    container_name: test_api_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=postgres
    ports:
      - '5444:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
